#!/bin/bash

export VAGRANT_EXPERIMENTAL=disks
export DEFAULT_INTERFACE=$(ip route list default | sed -e 's/.*dev \(\w\+\) .*/\1/' || echo eth0)

echo Found network interface: $DEFAULT_INTERFACE

vagrant destroy -f
vagrant up
sleep 3

ip=$(vagrant ssh -c "ip --json a show dev eth1 | jq '.[0]|.addr_info|.[]|select(.family == \"inet\")|.local' -r" | tr -d \\r)
host=app-0
comm="# terraform-module-provisioner $host"

if grep -q $host.kubespray /etc/hosts; then
    sudo cp -vf /etc/hosts /etc/hosts.bkp
    sudo sed -i -e "s/.*${comm}/$ip $host $host.kubespray $comm/" /etc/hosts
else
    echo "$ip $host $host.kubespray $comm" | sudo tee -a /etc/hosts
fi
